source = ~/.config/caelestia/repo-path.conf

$source_dir = $root_dir/dotfiles/.config/caelestia/modules
$UI = $source_dir/ui
$UX = $source_dir/ux

$mainMod = SUPER

$terminal = foot
$browser = brave
$file_manager = thunar
$volume_control = pavucontrol
